### ISSUE TITLE
`GuiLoadStyle()` fails to load font when using an absolute path

### ISSUE THREAD

**Issue by Demizdor** [raysan5/raygui#110]
```c
GuiLoadStyle("style.rgs"); // Loads the font
GuiLoadStyle("/home/adrian/style.rgs"); //Loads the style but fails to load the font
```
Hi @raysan5 , this issue was tested only on Linux and might affect only Linux, it only occurs when using absolute paths when loading a style. The problem is that `GetDirectoryPath()` adds a `./` in front of a path when it doesn't find a `:`, this might work on windows but it obviously fails on Linux.

So in the above example the first call to `GuiLoadStyle()` will look for the font in ".//style.font" which expanded will become "//home/adrian/style.font" so it will work while the second call to load the style will look in ".//home/adrian/style.font" but because of the `./` in front it  will get expanded to "//home/adrian/home/adrian/style.font" which is wrong

Problem is with the code starting here https://github.com/raysan5/raylib/blob/0c29ca8166f26ef24311fab5e2fd614f9358ea76/src/core.c#L2094

This behaviour is also present in https://github.com/raysan5/raygui/pull/109 for `GuiLoadSkin()` so when you decide on a fix it should work there too. In the skin editor i made it work with an ugly hack by setting the current director to `/` but this breaks a lot of things including taking a screenshot so it needs to be fixed as fast as possible.

I know this is mostly a raylib issue but since it affects raygui too i posted it here.

**Comment by Demizdor** [comment]
I think this issue with `GetDirectoryPath()` was solved in raylib.

**Comment by colesnicov** [comment]
Hello.It's not solved.

I have raylib **3.8-dev** and have same **problem with fonts!**
